### GET /api/healthcheck
GET http://localhost:8000/
###
GET http://localhost:8000/users
###
DELETE http://localhost:8000/users/"20"
###
POST http://localhost:8000/users
Content-Type: application/json

{
  "fullname": "Jane Doez",
  "email": "jane@gmailz.com",
  "role": "Inern"
}

###
PATCH http://localhost:8000/users/20
Content-Type: application/json

{
  "name": "kelcho",
  "email": "kelcho@gmail.com",
  "role": "Admin"
}

###
GET http://localhost:8000/users/1000
###

###
GET http://localhost:8000/users?role=admin&limit=2