### Health Check
GET http://localhost:8000/api/v1/health

### Users CRUD Operations ###

### Create User
POST http://localhost:8000/api/v1/users
Content-Type: application/json

{
  "username": "Kevindoe",
  "email": "Kevin@example.com",
  "password_hash": "secretpass123",
  "role": "INTERN"
}

### Get All Users
GET http://localhost:8000/api/v1/users

### Get User by ID
GET http://localhost:8000/api/v1/users/1

### Get User by ID
GET http://localhost:8000/api/v1/users?role=ADMIN

### Get User by ID
GET http://localhost:8000/api/v1/users?role=ADMIN&limit=1

### Update User
PATCH http://localhost:8000/api/v1/users/1
Content-Type: application/json

{
  "username": "johnupdated",
  "email": "john.updated@example.com"
}

### Delete User
DELETE http://localhost:8000/api/v1/users/1

### Lists CRUD Operations ###

### Create List
POST http://localhost:8000/api/v1/lists
Content-Type: application/json

{
  "user_id": 5,
  "name": " Freshiadoe Urgent List",
  "category_id": 3
}

### Get All Lists
GET http://localhost:8000/api/v1/lists

### Get List by ID
GET http://localhost:8000/api/v1/lists/12222

### Update List
PATCH http://localhost:8000/api/v1/lists/1
Content-Type: application/json

{
  "name": "Updated Shopping List"
}

### Delete List
DELETE http://localhost:8000/api/v1/lists/1

### Categories CRUD Operations ###

### Create Category
POST http://localhost:8000/api/v1/categories
Content-Type: application/json

{
  "name": "Urgent"
}

### Get All Categories
GET http://localhost:8000/api/v1/categories

### Get Category by ID
GET http://localhost:8000/api/v1/categories/1

### Update Category
PATCH http://localhost:8000/api/v1/categories/1
Content-Type: application/json

{
  "name": "Work"
}

### Delete Category
DELETE http://localhost:8000/api/v1/categories/1

### Tasks CRUD Operations ###

### Create Task
POST http://localhost:8000/api/v1/tasks
Content-Type: application/json

{
    "list_id": 2,
    "category_id": 2,
   "title": "Doctor's appointment",
    "description": "Visit the doctor for annual checkup",
    "due_date": "2024-02-10T08:30:00Z",
    "priority": "HIGH",
    "completed": "NO"
}

### Get All Tasks
GET http://localhost:8000/api/v1/tasks
### Get All Tasks
GET http://localhost:8000/api/v1/tasks?priority=HIGH

### Get All Tasks
GET http://localhost:8000/api/v1/tasks?priority=HIGH&limit=1

### Get All Tasks
GET http://localhost:8000/api/v1/tasks?priority=MEDIUM&completed=NO&limit=4

### Get Task by ID
GET http://localhost:8000/api/v1/tasks/1

### Update Task
PATCH http://localhost:8000/api/v1/tasks/1
Content-Type: application/json

{
  "title": "Buy more groceries",
  "description": "Add cheese to the list",
  "priority": "HIGH"
}

### Delete Task
DELETE http://localhost:8000/api/v1/tasks/1

### Filter Tasks
GET http://localhost:8000/api/v1/tasks?priority=HIGH&category_id=1

### Get Tasks by List
GET http://localhost:8000/api/v1/lists/1/tasks

### Get User's Lists
GET http://localhost:8000/api/v1/users/1/lists