### GET /api/healthcheck
GET http://localhost:8000/
###
GET http://localhost:8000/employees
###
DELETE http://localhost:8000/users/"20"
###
POST http://localhost:8000/users
Content-Type: application/json

{
  "id" : 23,
  "name": "",
  "email": "kevin.com",
  "role": "INTERN"
}

###
PATCH http://localhost:8000/users/20
Content-Type: application/json

{
  "name": "kelcho",
  "email": "kelcho@gmail.com",
  "role": "Admin"
}

###
GET http://localhost:8000/users/1000
###

###
GET http://localhost:8000/users?role=kevin&limit=2


###
POST http://localhost:8000/employees
Content-Type: application/json

{
  "name": "Jane comba",
  "email": ".com",
  "role": "INTERN"
}